### ISSUE TITLE
Unsupported config option for services: 'postgres-12.1-alpine'

### ISSUE THREAD

**Issue by wathsala-vishwajith** [LordReigns/ASP-Web-api#1]
Running docker compose gives an error.
![image](https://user-images.githubusercontent.com/64484342/105534634-c8d38800-5d13-11eb-8a64-79ef27758af7.png)

Fresh install on WSL2 Ubuntu 20.04.

**Comment by wathsala-vishwajith** [comment]
docker-compose version 1.25.0

**Comment by LordReigns** [comment]
I have updated the docker-compose file to fix the above issue 😄 . @wathsala-vishwajith
